# -*- coding: utf-8 -*-
"""Technical Interview Template.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vwG7arJLBeOFEclL4-iKi1_VooKCo6X_
"""

import requests, zipfile, io

url = "https://github.com/shawnabankovich/technical-interview/releases/download/v1.1/casino_resort_dataset_v2.zip"

r = requests.get(url)
r.raise_for_status()

z = zipfile.ZipFile(io.BytesIO(r.content))
z.extractall("data/")